include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-nftappfilter
PKG_VERSION:=1.0.0
PKG_RELEASE:=1

PKG_LICENSE:=GPL-3.0-or-later
PKG_MAINTAINER:=snnh <欢迎赞助，数字人民币：0041008370910659>
PKG_BUILD_DEPENDS:= luci-compat

include $(INCLUDE_DIR)/package.mk

define Package/$(PKG_NAME)
  SECTION:=luci
  CATEGORY:=LuCI
  TITLE:=NFT App Filter - Block websites using nftables
  DEPENDS:=+nftables +luci-compat
endef

define Package/$(PKG_NAME)/description
  Luci application to block websites using nftables.
endef

define Build/Compile
endef

define Package/$(PKG_NAME)/install
	$(INSTALL_DIR)$(1)/usr/sbin
	$(INSTALL_BIN) ./files/usr/sbin/nftappfilter$(1)/usr/sbin/
	$(INSTALL_DIR)$(1)/etc/config
	$(INSTALL_CONF) ./files/etc/config/nftappfilter$(1)/etc/config/
	$(INSTALL_DIR)$(1)/etc/init.d
	$(INSTALL_BIN) ./files/etc/init.d/nftappfilter$(1)/etc/init.d/
	$(INSTALL_DIR)$(1)/usr/share/nftappfilter
	$(INSTALL_DATA) ./files/usr/share/nftappfilter/appblockrule.config$(1)/usr/share/nftappfilter/
	$(INSTALL_DIR)$(1)/usr/libexec
	$(INSTALL_BIN) ./files/usr/libexec/rpcd/nftappfilter$(1)/usr/libexec/rpcd/
	$(INSTALL_DIR)$(1)/www/luci-static/resources/view/nftappfilter
	$(CP) ./files/www/luci-static/resources/view/nftappfilter/*$(1)/www/luci-static/resources/view/nftappfilter/
endef

$(eval$(call BuildPackage,$(PKG_NAME)))