#!/bin/sh /etc/rc.common
# SPDX-License-Identifier: GPL-3.0-or-later

START=95
STOP=95

start() {
    /usr/sbin/nftappfilter start
}

stop() {
    /usr/sbin/nftappfilter stop
}

restart() {
    stop
    start
}
